### ISSUE TITLE
bypass

### ISSUE THREAD

**Issue by Joshohferftgh** [Quartinal/matrix#1]
just keeps showing looks like this page isn't allowed when i try to open it

**Comment by Joshohferftgh** [comment]
![Screenshot 2024-04-19 11 03 02 AM](https://github.com/Quartinal/matrix/assets/123502927/fd772bb4-3092-4279-8ae9-6ea3e4217ac9)

**Comment by Quartinal** [comment]
I'm not entirely sure what you're saying, but this Securly blocked page is on the **chrome-extension:** scheme (aka protocol) instead of the **https:** scheme. When the Securly blocked page is on the **chrome-extension:** scheme, it usually means it detects "unsafe" code from either a policy-enforced guideline or a native Securly-enforced guideline.
